[package]
name = "citra_engine"
version.workspace = true
edition = "2024"
license = "GPLv3"
license_file = "../LICENSE"

[lib]
name = "citra_engine"
path = "./src/lib.rs"
test = true

[dependencies]
glam = { version = "0.30.8", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
simd-json = "0.17.0"

[features]
fast-math = ["glam/fast-math"]
